### ISSUE TITLE
About the reproduction of the results in the paper

### ISSUE THREAD

**Issue by Sun-Jiahao** [CSIPlab/EBAD#1]
I'm interested in the fantastic result reported in the original paper(https://arxiv.org/pdf/2303.14304), so I try to reproduce the result in Tab1 by running `python attack_bb_det.py` as mentioned in `README.md` with the default parameters(iterw is changed to 5 to align with setting of tab1). 
```python
    parser.add_argument("--eps", type=int, default=10, help="perturbation level: 10,20,30,40,50")
    parser.add_argument("--iters", type=int, default=20, help="number of inner iterations: 5,6,10,20...")
    parser.add_argument("--root", type=str, default='result', help="the folder name of result")
    parser.add_argument("--victim", type=str, default='RetinaNet', help="victim model")
    parser.add_argument("--x", type=int, default=3, help="times alpha by x")
    parser.add_argument("--n_wb", type=int, default=2, help="number of models in the ensemble")
    parser.add_argument("--surrogate", type=str, default='Faster R-CNN', help="surrogate model when n_wb=1")
    parser.add_argument("--lr", type=float, default=1e-2, help="learning rate of w")
    parser.add_argument("--iterw", type=int, default=5, help="iterations of updating w")
    parser.add_argument("--dataset", type=str, default='voc', help="model dataset 'voc' or 'coco'. This will change the output range of detectors.")
    parser.add_argument("-single", action='store_true', help="only care about one obj")
    parser.add_argument("-no_balancing", action='store_true', help="do not balance weights at beginning")
```
Unfortunately, i get the following result which is unexpected(the ASR of RetinaNet should be 53.2%):
```
success rate (victim): 0.35943775100401604
success rate of Faster R-CNN: 0.8112449799196787
success rate of YOLOv3: 0.7008032128514057
success rate of RetinaNet: 0.35943775100401604
```
I understand that the result will be slightly different for randomness, but a large gap will be unexpected. I don't know if there's something wrong with my settings and I'd appreciate it very much if you can tell me.

**Comment by Sun-Jiahao** [comment]
when I run `python attack_bb_det.py -single`, I find that the result is similar with the reported one. So I wonder whether you use `-single` or not to get the reported result.

**Comment by YtengTan** [comment]
Hi Jiahao,

To reproduce the result for row "l_inf = 10, both Weight Balancing and Weight Optimization are checked" entry "RetinaNet" in Tab. 1, please run `python attack_bb_det.py -single --iterw 5`. 

As mentioned in paper section 4.2 first paragraph, we randomly select one object from the output of the victim model as the victim object and perturb it into a target object that does not exist in the original detection. 

Use `-single` to perform attacks on this setting, and do not use `-no_balancing`.

Hope that clarifies!
Yaoteng Tan

**Comment by Sun-Jiahao** [comment]
Thanks for your reply! :)

Actually, I have run `python attack_bb_det.py -single --iterw 5` as you mentioned. I print my arguments to make it clearer and the parameters are as follows:
```
Namespace(dataset='voc', eps=10, iters=20, iterw=5, lr=0.01, n_wb=2, no_balancing=False, root='result', single=True, surrogate='Faster R-CNN', victim='RetinaNet', x=3)
```

However, It didn't work out very well:
```
success rate (victim): 0.4578313253012048
success rate of Faster R-CNN: 0.893574297188755
success rate of YOLOv3: 0.821285140562249
success rate of RetinaNet: 0.4578313253012048
```

Is there anything wrong with my parameter setting? Or maybe it's influenced by the random selection?

**Comment by zikuicai** [comment]
Hi Jiahao,

The results presented in this paper were computed using the .npy files generated during the attacks. The initial experiments were conducted with the `--iterw 10` parameter, and the analysis was performed at various query levels utilizing the `analyze_results.py` script. We have uploaded the original log files in the `results_voc` folder, which served as the basis for collecting the original data.

For the sake of replication, we reran the experiment and achieved a 51% attack success rate on the Retina model, which closely aligns with the reported value in the paper. The success rate for whitebox surrogate models in the table represents the average across different blackbox models. It is important to note that the final attack accuracy can be influenced by the randomness resulting from the selection of victim objects. However, we anticipate that our methods consistently outperform the baseline and previous approaches by a significant margin.

If you have any further inquiries or require additional clarification, please do not hesitate to reach out to us.

**Comment by Sun-Jiahao** [comment]
@zikuicai Thanks for your kind reply and now I do know how to reproduce the result.

Unfortunately, I'm still confused becuase it is mentioned in this paper as follows:
> To align with [4] that uses 5 attack plans, we set the maximum query budget to Q = 5 in Tab. 1.

Since Tab1 uses the result reported in the previous paper, it is fairer to set the budget to 5 so that the results can be comparable.

Looking forward to your reply!

**Comment by zikuicai** [comment]
The numbers in table 1 are calculated at query budget Q = 5. You can refer to `analyze_results.py` for more details. We used `--iterw 10` so that we could calculate the attack success rate at varying budgets from 0-10.

**Comment by Sun-Jiahao** [comment]
Thank you very much for your explanation and I think I figure it out now.

Finally, congratulations on your paper acceptance by CVPR2023!
